export const mockUsers = [
  {
    id: 1,
    name: "lucas",
    displayname: "lucas santos",
    email: "lucassantos@example.com",
    password: "123456",
  },
  {
    id: 2,
    name: "maria",
    displayname: "maria silva",
    email: "mariasilva@example.com",
    password: "123456",
  },
  {
    id: 3,
    name: "pedro",
    displayname: "pedro sousa",
    email: "pedrosousa@example.com",
    password: "123456",
  },
  {
    id: 4,
    name: "ana",
    displayname: "ana silva",
    email: "anasilva@example.com",
    password: "123456",
  },
  {
    id: 5,
    name: "joao",
    displayname: "joao silva",
    email: "joaosilva@example.com",
    password: "123456",
  },
  {
    id: 6,
    name: "maria",
    displayname: "maria clara",
    email: "mariaclara@example.com",
    password: "123456",
  },
  {
    id: 7,
    name: "pedro",
    displayname: "pedro pinhares",
    email: "pedropinhares@example.com",
    password: "123456",
  },
  {
    id: 8,
    name: "ana",
    displayname: "ana maria",
    email: "anamaria@example.com",
    password: "123456",
  },
  {
    id: 9,
    name: "joao",
    displayname: "joao paulo",
    email: "joaopaulo@example.com",
    password: "123456",
  },
  {
    id: 10,
    name: "maria",
    displayname: "maria menezes",
    email: "mariamenezes@example.com",
    password: "123456",
  },
];
